<a href="https://colab.research.google.com/github/Tiberu2611/Machine-Learning/blob/main/Ba%CC%80i_t%C3%A2%CC%A3p_gi%C6%B0%CC%83a_ki%CC%80.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [17]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.linear_model import LogisticRegression

Câu 1: Hãy tải về tập dữ liệu:
1. Breast cancer
2. Wine

In [18]:
import pandas as pd
# đọc file csv 
datawine =  pd.read_csv('wine.data', sep=",")
X = datawine.iloc[:, :-1].values
y = datawine.iloc[:, -1].values
databreast =  pd.read_csv('breast-cancer-wisconsin.data', sep=",")
X = databreast.iloc[:, :-1].values
y = databreast.iloc[:, -1].values



In [19]:
#Chuyển đổi và xóa các ô trống 
datawine.replace("?", np.nan, inplace=True) 
datawine.dropna(inplace=True) 
datawine.sample(10)

1  14.23  1.71  2.43  15.6  127   2.8  3.06   .28  2.29  5.64  1.04  \
83   2  11.84  0.89  2.58  18.0   94  2.20  2.21  0.22  2.35  3.05  0.79   
154  3  13.17  5.19  2.32  22.0   93  1.74  0.63  0.61  1.55  7.90  0.60   
171  3  14.16  2.51  2.48  20.0   91  1.68  0.70  0.44  1.24  9.70  0.62   
156  3  12.45  3.03  2.64  27.0   97  1.90  0.58  0.63  1.14  7.50  0.67   
66   2  12.37  1.17  1.92  19.6   78  2.11  2.00  0.27  1.04  4.68  1.12   
99   2  12.08  2.08  1.70  17.5   97  2.23  2.17  0.26  1.40  3.30  1.27   
114  2  11.03  1.51  2.20  21.5   85  2.46  2.17  0.52  2.01  1.90  1.71   
39   1  13.56  1.71  2.31  16.2  117  3.15  3.29  0.34  2.34  6.13  0.95   
6    1  14.06  2.15  2.61  17.6  121  2.60  2.51  0.31  1.25  5.05  1.06   
164  3  13.73  4.36  2.26  22.5   88  1.28  0.47  0.52  1.15  6.62  0.78   

     3.92  1065  
83   3.08   520  
154  1.48   725  
171  1.71   660  
156  1.73   880  
66   3.48   510  
99   2.96   710  
114  2.87   407  
39   3.38   795  
6    3.58  1295  
164  1.75   520

In [20]:
#Chuyển đổi và xóa các ô trống 
databreast.replace("?", np.nan, inplace=True) 
databreast.dropna(inplace=True) 
databreast.sample(10)

1000025   5   1  1.1  1.2  2 1.3  3  1.4  1.5  2.1
668  1350423   5  10   10    8  5   5  7   10    1    4
267   324427  10   8    8    2  3   4  8    7    8    4
275   434518   3   1    1    1  2   1  2    1    1    2
565  1333104   3   1    2    1  2   1  3    1    1    2
602  1352663   5   4    6    8  4   1  8   10    1    4
472  1269574   4   1    1    1  2   1  1    1    1    2
68   1121732   1   1    1    1  2   1  3    2    1    2
87   1152331   4   1    1    1  2   1  3    1    1    2
409  1238021   1   1    1    1  2   1  2    1    1    2
331   770066   5   2    2    2  2   1  2    2    1    2

In [21]:
datawine

1  14.23  1.71  2.43  15.6  127   2.8  3.06   .28  2.29   5.64  1.04  \
0    1  13.20  1.78  2.14  11.2  100  2.65  2.76  0.26  1.28   4.38  1.05   
1    1  13.16  2.36  2.67  18.6  101  2.80  3.24  0.30  2.81   5.68  1.03   
2    1  14.37  1.95  2.50  16.8  113  3.85  3.49  0.24  2.18   7.80  0.86   
3    1  13.24  2.59  2.87  21.0  118  2.80  2.69  0.39  1.82   4.32  1.04   
4    1  14.20  1.76  2.45  15.2  112  3.27  3.39  0.34  1.97   6.75  1.05   
..  ..    ...   ...   ...   ...  ...   ...   ...   ...   ...    ...   ...   
172  3  13.71  5.65  2.45  20.5   95  1.68  0.61  0.52  1.06   7.70  0.64   
173  3  13.40  3.91  2.48  23.0  102  1.80  0.75  0.43  1.41   7.30  0.70   
174  3  13.27  4.28  2.26  20.0  120  1.59  0.69  0.43  1.35  10.20  0.59   
175  3  13.17  2.59  2.37  20.0  120  1.65  0.68  0.53  1.46   9.30  0.60   
176  3  14.13  4.10  2.74  24.5   96  2.05  0.76  0.56  1.35   9.20  0.61   

     3.92  1065  
0    3.40  1050  
1    3.17  1185  
2    3.45  1480  
3    2.93   735  
4    2.85  1450  
..    ...   ...  
172  1.74   740  
173  1.56   750  
174  1.56   835  
175  1.62   840  
176  1.60   560  

[177 rows x 14 columns]

Những dữ liệu này là kết quả phân tích hóa học của các loại rượu vang được trồng ở cùng một vùng ở Ý nhưng có nguồn gốc từ ba giống cây trồng khác nhau. Phân tích đã xác định số lượng của 13 thành phần được tìm thấy trong mỗi loại trong số ba loại rượu vang.

Các thuộc tính là

1 class (biến phân loại - biến nhãn lớp)

2 Alcohol

3 Malic acid

4 Ash

5 Alcalinity of ash

6 Magnesium

7 Flavonoids

8 Nonflavanoid phenols

9 Proanthocyanins

10 Color intensity

11 Hue

12 OD280/OD315 of diluted wines

13 Proline

Biến class có 3 nhãn lớp là 1,2 và 3. Trong đó nhãn lớp 1 có 59 quan sát, nhãn lớp 2 có 71 quan sát và nhãn lớp 3 có 48 quan sát.  (Mỗi quan sát chính là một dòng)

Ngoài biến class (cột đầu tiên), các biến còn lại đều là biến liên tục và có thể nằm ở các miền giá trị khác nhau

In [22]:
databreast


1000025  5   1  1.1  1.2  2 1.3   3  1.4  1.5  2.1
0    1002945  5   4    4    5  7  10   3    2    1    2
1    1015425  3   1    1    1  2   2   3    1    1    2
2    1016277  6   8    8    1  3   4   3    7    1    2
3    1017023  4   1    1    3  2   1   3    1    1    2
4    1017122  8  10   10    8  7  10   9    7    1    4
..       ... ..  ..  ...  ... ..  ..  ..  ...  ...  ...
693   776715  3   1    1    1  3   2   1    1    1    2
694   841769  2   1    1    1  2   1   1    1    1    2
695   888820  5  10   10    3  7   3   8   10    2    4
696   897471  4   8    6    4  3   4  10    6    1    4
697   897471  4   8    8    5  4   5  10    4    1    4

[682 rows x 11 columns]

1.1 Tập dữ liệu Breast Cancer Wisconsin
Bộ dữ liệu BCW chứa 699 mẫu bệnh phẩm được lấy từ các tế bào ung thư vú của bệnh nhân
Có 11 thuộc tính cho mỗi quan sát tương ứng với miền giá trị của nó

1 Sample code number (ID - Các con số dùng để định danh)

2 Clump Thickness (1-10) (Tức là giá trị của nó là số nguyên nằm từ 1 đến 10)

3 Uniformity of Cell Size (1-10)

4 Uniformity of Cell Shape (1-10)

5 Marginal Adhesion (1-10)

6 Single Epithelial Cell Size (1-10)

7 Bare Nuclei (1-10)

8 Bland Chromatin (1-10)

9 Normal Nucleoli (1-10)

10 Mitoses (1-10)

11 Class (2- cho bệnh lành tính và 4 - cho bệnh ác tính) 

Tập thuộc tính Class đóng vai trò nhãn lớp, chẩn đoán xem khối u lành tính hay ác tính.

Nhưng vì tập thuộc tính này thể hiện qua các giá trị 2 (lành tính) và 4 (ác tính) nên ta cần biến đổi từng giá trị thành các đặc trưng nhị phân chỉ chứa giá trị 0 và 1.
> **0 : lành tính**

> **1 : ác tính**


Câu 2: Đối với từng tập dữ liệu hãy xác định:
1. Thuộc tính nào đóng vai trò nhãn lớp?

  -Biến class đóng vai trò nhãn lớp
2. Tập dữ liệu nào phục vụ bài toán phân lớp nhị phân? Bài toán phân lớp đa nhãn?

  -Tập dữ liệu breast phục vụ cho bài toán nhị phân

  -Tập dữ liệu wine phục vụ cho bài toán phân lớp đa nhãm

3. Thuộc tính nào không cần thiết trong huấn luyện mô hình?

  -Thuộc tính id là không cần thiết trong huấn luyện mô hình


Câu 3: Hãy xây dựng mô hình phân lớp LogisticRegression, k-NN và Naïve Bayes cho 2 tập dữ
liệu trên. Yêu cầu:
1. Xác định nhãn lớp có cân bằng hay không?
2. Phân chia train – test theo tỉ lệ 80% - 20% có cần thực hiện xáo trộn dữ liệu hay không?
3. Thông báo kết quả 10-fold CV của quá trình huấn luyện từng mô hình (sử dụng
cross_val_scores)
4. Dựa vào kết quả dự đoán của từng mô hình - ŷ và tập dữ liệu kiểm chứng - ytest, hãy:

a. Đánh giá hiệu năng của từng mô hình theo các bộ chỉ số: (i) accuracy; (ii) precision; (iii) recall; và (iv) f1-measure.

b. Vẽ bảng ghi kết quả so sánh các chỉ số trên của từng mô hình

c. Xác định mô hình vượt trội?

In [23]:
# nhãn lớp cân bằng
from sklearn import datasets
import numpy as np
 
X = datawine.iloc[:, :-1].values
y = datawine.iloc[:, -1].values
 
X_imb = np.vstack((X[y == 1], X[y == 0][:30]))
y_imb = np.hstack((y[y == 1], y[y == 0][:30]))


In [24]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)


In [25]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
X[:, 1:3] = imputer.fit_transform(X[:, 1:3])

In [26]:
X_train

array([[ 1.  , 13.07,  1.5 , ...,  3.7 ,  1.18,  2.69],
       [ 3.  , 13.78,  2.76, ...,  9.58,  0.7 ,  1.68],
       [ 3.  , 13.27,  4.28, ..., 10.2 ,  0.59,  1.56],
       ...,
       [ 1.  , 13.39,  1.77, ...,  4.8 ,  0.92,  3.22],
       [ 2.  , 12.29,  1.41, ...,  2.9 ,  1.23,  2.74],
       [ 2.  , 11.56,  2.05, ...,  6.  ,  0.93,  3.69]])

In [27]:
y_train


array([1020,  615,  835,  428,  515,  718,  830,  515,  675,  378,  855,
       1295,  480,  365,  640,  278,  840,  500,  680,  570, 1480, 1547,
        406, 1450,  415, 1290,  630,  325,  650, 1260,  725,  845,  710,
        795,  510,  410, 1680,  510, 1080, 1045,  630,  550,  438,  520,
        600,  750,  495,  750,  750, 1310, 1285, 1375,  985,  480,  937,
        625,  886, 1280,  315,  380,  880,  625,  760,  312,  714,  845,
       1265,  345,  625,  495,  780, 1015,  675,  415,  885,  660,  660,
        680,  420, 1285,  695,  620, 1130, 1060,  480,  780, 1510,  680,
       1035,  920,  580,  434,  392,  345,  590, 1035,  560,  990,  630,
        562,  830,  450,  770, 1050,  660,  562, 1150,  502,  564, 1235,
        407, 1035,  520,  560,  530, 1280, 1095, 1190,  385,  870,  680,
        500,  607, 1045,  352,  580,  488,  495, 1095,  680, 1185,  880,
        425,  915,  562,  470,  520,  520, 1195,  428,  465])

In [28]:
X_test

array([[  2.  ,  12.37,   1.17,   1.92,  19.6 ,  78.  ,   2.11,   2.  ,
          0.27,   1.04,   4.68,   1.12,   3.48],
       [  2.  ,  12.67,   0.98,   2.24,  18.  ,  99.  ,   2.2 ,   1.94,
          0.3 ,   1.46,   2.62,   1.23,   3.16],
       [  1.  ,  13.74,   1.67,   2.25,  16.4 , 118.  ,   2.6 ,   2.9 ,
          0.21,   1.62,   5.85,   0.92,   3.2 ],
       [  1.  ,  13.05,   1.73,   2.04,  12.4 ,  92.  ,   2.72,   3.27,
          0.17,   2.91,   7.2 ,   1.12,   2.91],
       [  1.  ,  14.22,   1.7 ,   2.3 ,  16.3 , 118.  ,   3.2 ,   3.  ,
          0.26,   2.03,   6.38,   0.94,   3.31],
       [  2.  ,  12.64,   1.36,   2.02,  16.8 , 100.  ,   2.02,   1.41,
          0.53,   0.62,   5.75,   0.98,   1.59],
       [  1.  ,  13.05,   1.65,   2.55,  18.  ,  98.  ,   2.45,   2.43,
          0.29,   1.44,   4.25,   1.12,   2.51],
       [  3.  ,  13.32,   3.24,   2.38,  21.5 ,  92.  ,   1.93,   0.76,
          0.45,   1.25,   8.42,   0.55,   1.62],
       [  1.  ,  14.38,   3.59, 

In [29]:
y_test

array([ 510,  450, 1060, 1150,  970,  450, 1105,  650, 1065, 1285,  985,
        740,  355,  290,  695,  372,  342,  463, 1515,  630,  520, 1120,
        720,  472, 1270,  685,  625,  750,  550,  672,  380,  735,  466,
        600, 1320,  678])