<a href="https://colab.research.google.com/github/Tiberu2611/Machine-Learning/blob/main/BTVN2_Vector_Ma_tr%E1%BA%ADn_Tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

BÀI ÔN TẬP KIẾN THỨC TOÁN VÀ LẬP TRÌNH

1.Các phép toán với vector

In [1]:
import numpy as np

Cộng 2 vector

In [2]:
x = np.array([1,2,3,4])
y = np.array([5,3,2,1])
z = x+y

In [3]:
print(z)

[6 5 5 5]


In [4]:
#kích thước vector 
print(z.ndim)

1


In [5]:
#số chiều của vector
print(z.shape)

(4,)


Phép nhân đại lượng vô hướng với vector trong Python

In [6]:
x = np.array([1, 2, 3, 4])
a = 15
z = a*x

In [7]:
print(z)

[15 30 45 60]


In [8]:
#số chiều của vector
print(z.ndim)

1


In [9]:
#kích thước vector 
print(z.shape)

(4,)


Tích vô hướng của 2 vector

In [10]:
x = np.array([1, 2, 3, 4])
y = np.array([5, 3, 2, 1])
z = np.dot(x,y)

In [11]:
print(z)

21


In [12]:
#số chiều của vector
print(z.ndim)

0


In [13]:
#kích thước vector 
print(z.shape)

()


Tích hữu hướng của 2 vector

In [14]:
x = np.array([1,2,3])
y = np.array([3,2,1])
z = np.cross(x, y)

In [15]:
print(z)

[-4  8 -4]


In [16]:
#số chiều của vector
print(z.ndim)

1


In [17]:
#kích thước vector 
print(z.shape)

(3,)


Phép nhân các phần tử có vị trí tương ứng (elementwise multiplication) 2 vector

In [18]:
x = np.array([1,2,3,4])
y = np.array([5,3,2,1])
z = np.multiply(x,y)

In [19]:
print(z)

[5 6 6 4]


In [20]:
#số chiều của vector
print(z.ndim)

1


In [21]:
#kích thước vector 
print(z.shape)

(4,)


2.Các phép toán với ma trận

Phép cộng 2 ma trận

In [22]:
X = np.array([1,2,3,4,5,6]).reshape((2,3))
Y = np.array([6,5,4,3,2,1]).reshape((2,3))
Z = X + Y

In [23]:
print(Z)

[[7 7 7]
 [7 7 7]]


In [24]:
#số chiều và kích thước của ma trận 
print(Z.ndim,';',Z.shape)

2 ; (2, 3)


Phép nhân ma trận với 1 đại lượng vô hướng

In [25]:
X = np.array([1,2,3,4,5,6]).reshape((2,3))
a = 2
Z = a*X

In [26]:
print(Z)

[[ 2  4  6]
 [ 8 10 12]]


In [27]:
#số chiều và kích thước của ma trận 
print(Z.ndim,';',Z.shape)

2 ; (2, 3)


Phép chuyển vị ma trận (transpose)

In [28]:
X = np.array([1,2,3,4,5,6]).reshape((2,3))
Z = X.T

In [29]:
print(Z)

[[1 4]
 [2 5]
 [3 6]]


In [30]:
#số chiều và kích thước của ma trận 
print(Z.ndim,';',Z.shape)

2 ; (3, 2)


Phép nhân 2 ma trận

In [31]:
X = np.array([1,2,3,4,5,6]).reshape((2,3))
Y = np.array([6,5,4,3,2,1]).reshape((3,2))
Z = np.dot(X,Y)

In [32]:
print(Z)

[[20 14]
 [56 41]]


In [33]:
#số chiều và kích thước của ma trận 
print(Z.ndim,';',Z.shape)

2 ; (2, 2)


Phép nhân các phần tử có vị trí tương đương (elementwise multiplication) của 2 ma trận

In [34]:
X = np.array([1,2,3,4,5,6]).reshape((2,3))
Y = np.array([6,5,4,3,2,1]).reshape((2,3))
Z = X*Y

In [35]:
print(Z)

[[ 6 10 12]
 [12 10  6]]


In [36]:
#số chiều và kích thước của ma trận 
print(Z.ndim,';',Z.shape)

2 ; (2, 3)


Tạo ma trận cột dạng đặc biệt $R^{m1}$*

In [37]:
x = np.array([1,2,3,4,5]).reshape((5,1))

In [38]:
print(x)

[[1]
 [2]
 [3]
 [4]
 [5]]


In [39]:
#số chiều và kích thước của vector 
print(x.ndim,';',x.shape)

2 ; (5, 1)


Lấy ra 1 vector hàng từ ma trận X và chuyển thành ma trận đặc biệt dạng $R^{n×1}$

In [40]:
X = np.array([1,2,3,4,5,6]).reshape((2,3))
m = X.shape[0]
n = X.shape[1]
print('m = ', m, '; n = ', n)

m =  2 ; n =  3


In [41]:
x = X[0, :]
print(x)

[1 2 3]


In [42]:
print(x.ndim, '; ', x.shape)

1 ;  (3,)


In [43]:
x = x.reshape((1,n))
print(x)

[[1 2 3]]


In [44]:
print(x.ndim, '; ', x.shape)

2 ;  (1, 3)


Lấy ra 1 vector cột từ ma trận X và chuyển thành ma trận đặc biệt dạng $R^{m×1}$

In [45]:
X = np.array([1,2,3,4,5,6]).reshape((2,3))
m = X.shape[0]
n = X.shape[1]
print('m = ', m, '; n = ', n)

m =  2 ; n =  3


In [46]:
x = X[:,1]
print(x)

[2 5]


In [47]:
print(x.ndim, '; ', x.shape)

1 ;  (2,)


In [48]:
x = x.reshape((m,1))
print(x)

[[2]
 [5]]


In [49]:
print(x.ndim, '; ', x.shape)

2 ;  (2, 1)


Xếp thêm 1 vector cột vào đầu ma trận : x ∈ $R^m$ hay x ∈ $R^{m×1}$, X ∈ $R^{m×n}$,
X = [x,X]

In [50]:
X=np.array([1,2,3,4,5,6,7,8,9,10,11,12]).reshape((4,3))
x = np.array([1,1,1,1]).reshape((4,1))
X = np.column_stack([x,X])
print(X)
#số chiều và kích thước của ma trận
print(X.ndim, '; ', X.shape)

[[ 1  1  2  3]
 [ 1  4  5  6]
 [ 1  7  8  9]
 [ 1 10 11 12]]
2 ;  (4, 4)


Tách 1 ma trận data ban đầu gồm n cột thành 1 ma trận con X chứa cácn-1 cột đầu tiên và 1 vector cột y lấy ra từ cột cuối cùng của data

In [51]:
data = np.array([[10,22,13,1],
[9,6,5,0],
[8,12,4,1],
[6,5,7,0]])
X = data[:,:-1]
y = data[:,-1].reshape((data.shape[0], 1))
print(X)
print(X.ndim, '; ', X.shape)

[[10 22 13]
 [ 9  6  5]
 [ 8 12  4]
 [ 6  5  7]]
2 ;  (4, 3)


In [52]:
print(y)
print(y.ndim, '; ', y.shape)

[[1]
 [0]
 [1]
 [0]]
2 ;  (4, 1)


3. Các phép toán với tensor hạng cao (≥
3)

Tạo 1 tensor T ∈ $R^{m×n×k}$ với m = 2, n= 2 và k = 3, các giá trị được sinh ngẫu nhiên. 

In [53]:
import numpy as np
m=2
n=2
k=3
T = np.random.randint(low=0,high=5,size=m*n*k).reshape(m,n,k)
print(T)

[[[2 1 1]
  [1 0 0]]

 [[1 4 4]
  [2 1 3]]]


In [54]:
print(T.shape)

(2, 2, 3)


Tạo 1 tensor T2 ∈ $R^{m×n×k×q}$ chứa 2 tensor t1,t2 ∈ $R^{m×n×k}$, biết t1 và t2 được sinh ngẫu nhiên

In [55]:
import numpy as np
m=2
n=2
k=3
t1 = np.random.randint(low=0,high=5,size=m*n*k).reshape(m,n,k)
t2 = np.random.randint(low=0,high=5,size=m*n*k).reshape(m,n,k)
T2 = np.stack((t1, t2), axis=0)
print(T2)

[[[[0 4 1]
   [2 2 1]]

  [[4 4 0]
   [3 4 1]]]


 [[[1 1 4]
   [4 1 1]]

  [[4 3 1]
   [2 1 0]]]]


In [56]:
print(T2.shape)

(2, 2, 2, 3)
